name: e_shop
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  fluttertoast: ^8.0.7
  image: ^3.1.1
  image_picker: ^0.8.4+5
  intl: null
  path_provider: ^2.0.8
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
